### ISSUE TITLE
Unable to download dataset from baidu link

### ISSUE THREAD

**Issue by FawadAbbas12** [VisDrone/DroneRGBT#5]
啊哦，你所访问的页面不存在了。

可能的原因：
1.在地址栏中输入了错误的地址。
2.你点击的某个链接已过期。

**Comment by fatbringer** [comment]
Same problem!

**Comment by zhouyizhuo** [comment]
@FawadAbbas12 @fatbringer 你们找到数据集了吗

**Comment by FawadAbbas12** [comment]
> @FawadAbbas12 @fatbringer 你们找到数据集了吗
No i haven't

**Comment by VisDrone** [comment]
Dataset link has been updated

**Comment by ykn96** [comment]
@VisDrone thanks
